"""Shapes the Indian film's Hindi chapter headings into 3D-ready outlines: src/lib/deva-headings.js.

three.js's TextGeometry cannot shape Devanagari (conjuncts, matras, reph), so each word is shaped
here with HarfBuzz on GNU FreeSerif Bold, split into its aksharas (HarfBuzz clusters: the pieces
that fly in one by one, like the Latin headings' letters), each akshara's glyphs merged into clean
outlines with skia-pathops, and written in the three.js typeface outline syntax ('m', 'l', 'q', 'b').

Usage: python3 tools/deva-headings.py [font.ttf]
(needs: pip install uharfbuzz skia-pathops fonttools)
"""
import json
import re
import sys
from pathlib import Path

import pathops
import uharfbuzz as hb
from fontTools.pens.recordingPen import RecordingPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FONT = sys.argv[1] if len(sys.argv) > 1 else '/usr/share/fonts/truetype/freefont/FreeSerifBold.ttf'
OUT = ROOT / 'src/lib/deva-headings.js'

# the words: WORDS_HI in src/films/india.js (read from there so the two never drift apart)
src = (ROOT / 'src/films/india.js').read_text()
block = re.search(r'const WORDS_HI = \{(.*?)\};', src, re.S).group(1)
WORDS = re.findall(r"'([^']+)'", block)
WORDS = [w for w in WORDS if re.search('[ऀ-ॿ]', w)]

blob = hb.Blob.from_file_path(FONT)
face = hb.Face(blob)
hbfont = hb.Font(face)
tt = TTFont(FONT)
gs = tt.getGlyphSet()
order = tt.getGlyphOrder()
upem = tt['head'].unitsPerEm
S = 1000 / upem


def shape(word):
    buf = hb.Buffer()
    buf.add_str(word)
    buf.guess_segment_properties()
    hb.shape(hbfont, buf, {})
    return buf.glyph_infos, buf.glyph_positions


def outline(path):
    """pathops Path -> three.js typeface 'o' string (font units scaled to 1000/em)."""
    rec = RecordingPen()
    path.draw(rec)
    o = []
    r = lambda v: f'{v * S:.1f}'.rstrip('0').rstrip('.')
    cur = None
    for op, pts in rec.value:
        if op == 'moveTo':
            cur = pts[0]
            o.append(f'm {r(cur[0])} {r(cur[1])}')
        elif op == 'lineTo':
            cur = pts[0]
            o.append(f'l {r(cur[0])} {r(cur[1])}')
        elif op == 'qCurveTo':
            # TrueType implied on-curve points between consecutive off-curve points
            offs, end = list(pts[:-1]), pts[-1]
            for i, c in enumerate(offs):
                e = end if i == len(offs) - 1 else ((c[0] + offs[i + 1][0]) / 2, (c[1] + offs[i + 1][1]) / 2)
                o.append(f'q {r(e[0])} {r(e[1])} {r(c[0])} {r(c[1])}')
            cur = end
        elif op == 'curveTo':
            c1, c2, e = pts
            o.append(f'b {r(e[0])} {r(e[1])} {r(c1[0])} {r(c1[1])} {r(c2[0])} {r(c2[1])}')
            cur = e
        elif op in ('closePath', 'endPath'):
            o.append('z')
    return ' '.join(o)


words = {}
for w in WORDS:
    infos, poss = shape(w)
    x = 0
    clusters = {}
    for info, pos in zip(infos, poss):
        p = clusters.setdefault(info.cluster, pathops.Path())
        pen = TransformPen(p.getPen(), (1, 0, 0, 1, x + pos.x_offset, pos.y_offset))
        gs[order[info.codepoint]].draw(pen)
        x += pos.x_advance
    out = []
    lo, hi = 1e9, -1e9
    for k in sorted(clusters):
        p = clusters[k]
        # merge the akshara's overlapping glyphs (matra over consonant, headline joins) into clean
        # outlines, outer contours clockwise as three's typeface outlines expect
        p = pathops.simplify(p, clockwise=True)
        b = p.bounds
        if b[2] <= b[0]:
            continue
        lo, hi = min(lo, b[1]), max(hi, b[3])
        out.append({'x0': round(b[0] * S, 1), 'x1': round(b[2] * S, 1), 'o': outline(p)})
    words[w] = {'width': round(x * S, 1), 'bottom': round(lo * S, 1), 'top': round(hi * S, 1), 'clusters': out}
    print(w, len(out), 'aksharas', round(x * S))

# the headline (shirorekha) height: the top of the bar on क — headings are sized by it
gid = hbfont.get_nominal_glyph(0x0915)
bar = gs[order[gid]]
rp = pathops.Path()
bar.draw(rp.getPen())
head = round(rp.bounds[3] * S, 1)

OUT.write_text(
    '// GENERATED by tools/deva-headings.py — the Indian film\'s Hindi chapter headings, shaped with HarfBuzz\n'
    '// from GNU FreeSerif Bold (GPL with font exception; see assets/fonts/LICENSE-freeserif.txt).\n'
    '// Per word: its aksharas as three.js typeface outlines (1000 units/em, baseline y = 0).\n'
    f'export default {json.dumps({"resolution": 1000, "headline": head, "words": words}, ensure_ascii=False, separators=(",", ":"))};\n')
print('wrote', OUT, OUT.stat().st_size, 'bytes; headline', head)
